import os

l =[

"D:\IPL\Assets\Players\Abhishek_Sharma.jpg"
,"D:\IPL\Assets\Players\Ambati Rayudu.jpg"
,"D:\IPL\Assets\Players\Amit_Mishra.jpg"
,"D:\IPL\Assets\Players\Avesh_Khan.jpg"
,"D:\IPL\Assets\Players\Chris_Morris.jpg"
,"D:\IPL\Assets\Players\Colin_Munro.jpg"
,"D:\IPL\Assets\Players\Dan_Christian.jpg"
,"D:\IPL\Assets\Players\David Willey.jpg"
,"D:\IPL\Assets\Players\Deepak Chahar.jpg"
,"D:\IPL\Assets\Players\Deepak Punia.jpg"
,"D:\IPL\Assets\Players\Dhruv Shorey.jpg"
,"D:\IPL\Assets\Players\Dwayne Bravo.jpg"
,"D:\IPL\Assets\Players\Faf du Plessis.jpg"
,"D:\IPL\Assets\Players\Gautam_Gambhir.jpg"
,"D:\IPL\Assets\Players\Glenn_Maxwell.jpg"
,"D:\IPL\Assets\Players\Gurkeerat_Mann_Singh.jpg"
,"D:\IPL\Assets\Players\Harbhajan Singh.jpg"
,"D:\IPL\Assets\Players\Hardik Pandya.jpg"
,"D:\IPL\Assets\Players\Harshal_Patel.jpg"
,"D:\IPL\Assets\Players\Imran Tahir.jpg"
,"D:\IPL\Assets\Players\Jagadeesha Suchith.jpg"
,"D:\IPL\Assets\Players\Jason_Roy.jpg"
,"D:\IPL\Assets\Players\Jasprit Bumrah.jpg"
,"D:\IPL\Assets\Players\Jayant_Yadav.jpg"
,"D:\IPL\Assets\Players\Jitesh Sharma.jpg"
,"D:\IPL\Assets\Players\Jos Buttler.jpg"
,"D:\IPL\Assets\Players\Junior_Dala.jpg"
,"D:\IPL\Assets\Players\Karn Sharma.jpg"
,"D:\IPL\Assets\Players\Kedar Jadhav.jpg"
,"D:\IPL\Assets\Players\Kieron Pollard.jpg"
,"D:\IPL\Assets\Players\KM Asif.jpg"
,"D:\IPL\Assets\Players\Krishnappa Gowtham.jpg"
,"D:\IPL\Assets\Players\Krunal Pandya.jpg"
,"D:\IPL\Assets\Players\Kulwant Khejroliya.jpg"
,"D:\IPL\Assets\Players\Lasith Malinga.jpg"
,"D:\IPL\Assets\Players\Lendl Simmons.jpg"
,"D:\IPL\Assets\Players\Liam_Plunkett.jpg"
,"D:\IPL\Assets\Players\Lungi Ngidi.jpg"
,"D:\IPL\Assets\Players\Mark Wood.jpg"
,"D:\IPL\Assets\Players\Mitchell Johnson.jpg"
,"D:\IPL\Assets\Players\Mitchell McClenaghan.jpg"
,"D:\IPL\Assets\Players\Mitchell Santner.jpg"
,"D:\IPL\Assets\Players\Mohammad_Shami.jpg"
,"D:\IPL\Assets\Players\Monu Kumar.jpg"
,"D:\IPL\Assets\Players\MS Dhoni.jpg"
,"D:\IPL\Assets\Players\Murali Vijay.jpg"

,"D:\IPL\Assets\Players\Parthiv Patel.jpg"
,"D:\IPL\Assets\Players\Prithvi_Shaw.jpg"
,"D:\IPL\Assets\Players\Rahul_Tewatia.jpg"
,"D:\IPL\Assets\Players\Ravindra Jadeja.jpg"

,"D:\IPL\Assets\Players\Rishabh_Pant.jpg"
,"D:\IPL\Assets\Players\Rohit Sharma.jpg"
,"D:\IPL\Assets\Players\Sam Billings.jpg"
,"D:\IPL\Assets\Players\Sandeep_Lamichhane.jpg"
,"D:\IPL\Assets\Players\Saurabh Tiwary.jpg"
,"D:\IPL\Assets\Players\Shahbaz_Nadeem.jpg"
,"D:\IPL\Assets\Players\Shane Watson.jpg"
,"D:\IPL\Assets\Players\Shardul Thakur.jpg"
,"D:\IPL\Assets\Players\Shreyas_Iyer.jpg"
,"D:\IPL\Assets\Players\Siddhesh Lad.jpg"
,"D:\IPL\Assets\Players\Suresh Raina.jpg"
,"D:\IPL\Assets\Players\Trent_Boult.jpg"
,"D:\IPL\Assets\Players\Vijay_Shankar.jpg"
,"D:\IPL\Assets\Players\Vinay Kumar.jpg"
]

for i in l:
    new = i.replace(' ','_')
    os.rename(i,new)